---
title: "Projects"
---

```{r}
#| echo: false
source("R/add_cards.R")
```

::: {.grid}
```{r}
#| echo: false
#| results: asis

# feathers
add_card_projects(
  img = "images/dove.png",
  title = "feathers", 
  text = "[feathers]{.monosp} is an R package that contains colour palettes inspired by the plumage of Australian birds. For species exhibiting sexual dimorphism, I have used female colours.",
  url = "https://github.com/shandiya/feathers"
)

# variations on a theme
add_card_projects(
  img = "images/bauhaus.png",
  title = "Variations on a theme", 
  text = "Sometimes I make art in R ([rtistry]{.monosp}). These projects are spaces for me to explore a single idea and experiment with code.",
  url = "https://github.com/shandiya/variations-on-a-theme"
)

# victual verses
add_card_projects(
  img = "images/verse.png",
  title = "VictualVerses", 
  text = "A Shiny app that generates three-line verses in the style of haiku. A random word is chosen from \"Mrs. Beeton's Dictionary of Every-Day Cookery\", and the following 17 syllables are output in lines of 5-7-5(ish) syllables.",
  url = "https://shandiya.shinyapps.io/victualverses/"
)

# manky parrots
add_card_projects(
  img = "images/lorikeet.png",
  title = "Manky Parrots", 
  text = "Manky Parrots is a citizen science project that maps the incidence of psittacine beak and feather disease (PBFD) in Australia to understand the spread of the disease in the wild.",
  url = "https://biocollect.ala.org.au/acsa/project/index/71330a55-a91a-4456-90b7-9de7bd8ac08d"
)
   
# misc
add_card_projects(
  img = "images/volcanoes.png",
  title = "misc.", 
  text = "Links to repositories where I've dabbled in [this](https://github.com/shandiya/project_euler), [that](https://github.com/shandiya/advent-of-code), and [the other](https://github.com/shandiya/genuary2021). Sometimes they involve [maps](https://github.com/shandiya/30DayMapChallenge), [sometimes not](https://github.com/shandiya/TidyTuesday).",
  url = "https://github.com/shandiya/TidyTuesday/tree/master/2020-3-volcanoes"
)

# koel
add_card_projects(
  img = "images/koel.png",
  title = "koel", 
  text = "[koel]{.monosp} contains a set of functions that facilitate the process of retrieving and summarising biodiversity data within spatial and temporal constraints, and emailing these data as a summary table.",
  url = "https://github.com/AtlasOfLivingAustralia/koel"
)

```
:::
