---
title: "Publications"
format:
  html:
    toc: true
    toc-location: left
    toc-title: " "
---

### Peer-reviewed publications

Roger E, Turley A, Waite C, **Balasubramaniam S**, Slatyer C, Pearce JA (2024) Citizen science delivers high-value biosecurity surveillance and reporting capability. *Wildlife Research* 51: WR24046. doi: [10.1071/WR24046](https://doi.org/10.1071/WR24046)

Boysen K, Perkins SL, Hunjan S, Oliver P, Gardner M, **Balasubramaniam S**, J Melville (2022) Diversity and phylogenetic relationships of haemosporidian and hemogregarine parasites in Australian lizards. *Molecular Phylogenetics and Evolution* 167: 107358. doi: [10.1016/j.ympev.2021.107358](https://doi.org/10.1016/j.ympev.2021.107358)

**Balasubramaniam S**, Mulder RA, Sunnucks P, Pavlova A, Melville J (2017) MHC class II β exon 2 variation in pardalotes (Pardalotidae) is shaped by selection, recombination and gene conversion. *Immunogenetics* 69: 101-111. doi: [10.1007/s00251-016-0953-7](https://doi.org/10.1007/s00251-016-0953-7)

**Balasubramaniam S**, Bray RD, Mulder RA, Sunnucks P, Pavlova A, Melville J (2016) New data from basal Australian songbird lineages show that complex structure of MHC class II β genes has early evolutionary origins within passerines. *BMC Evolutionary Biology* 16:112. doi: [10.1186/s12862-016-0681-5](https://doi.org/10.1186/s12862-016-0681-5)

**Balasubramaniam S**, Mulder RA, Sunnucks P, Pavlova A, Amos JN, Melville J (2013) Prevalence and diversity of avian haematozoa in three species of Australian passerine. *Emu* 113:353-358. doi: [10.1071/MU13012](https://doi.org/10.1071/MU13012)

Amos N, **Balasubramaniam S**, Grootendorst L, Harrisson K, Lill A, Mac Nally RC, Pavlova A, Radford JQ, Takeuchi N, Thomson JR, Sunnucks P (2013) Little evidence that condition, stress indicators, sex ratio, or homozygosity are related to landscape or habitat attributes in declining woodland birds. *Journal of Avian Biology* 44:45-54. doi: [10.1111/j.1600-048X.2012.05746.x](https://doi.org/10.1111/j.1600-048X.2012.05746.x)

**Balasubramaniam S**, Guay P-J (2008) Purple swamphens (*Porphyrio porphyrio*) attempting to prey upon black swan (*Cygnus atratus*) eggs and preying upon a cygnet on an urban lake in Melbourne, Australia. *Wilson Journal of Ornithology* 120:633-635. doi: [10.1676/07-150.1](https://doi.org/10.1676/07-150.1)

### Technical reports

**Balasubramaniam S**, Sumner J (2021) Genetic analysis of captive and wild populations of the Bush Stone-curlew *Burhinus grallarius*. Technical report prepared for DELWP. 29 pp.

**Balasubramaniam S** (2020) Plains-wanderer genetic analysis: A comparison of wild and captive-bred individuals. Technical report prepared for Plains-wanderer National Recovery Team. 19 pp.

**Balasubramaniam S** (2020) Population structure in the Hooded Plover *Thinornis cucullatus*. Technical report prepared for BirdLife Australia. 18 pp.

Rowe K, **Balasubramaniam S** (2020) Plains-wanderer acoustic monitoring: song meter detection space. Technical report prepared for DELWP. 16 pp.

**Balasubramaniam S** (2019) Genetic analysis of the Plains-wanderer *Pedionomus torquatus*. Technical report prepared for Zoos Victoria and Taronga Conservation Society Australia. 19 pp.

### Theses

Balasubramaniam S (2016) Evolution and ecology of major histocompatibility complex (MHC) genes in south-eastern Australian passerines. Doctoral Thesis. School of BioSciences, The University of Melbourne.

Balasubramaniam S (2007) Male incubation effort and extra-pair paternity in the Black Swan (*Cygnus atratus*). Honours Thesis. School of BioSciences, The University of Melbourne.
